/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * 라이브러리를 사용할 때 Shared Library를 불러올 수 있도록 수정되었습니다.
 * ----------------------------------------------------------------------------- */
package org.chasen.mecab;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;

public class MeCab implements MeCabConstants {
    public static synchronized void initialize() {
        System.out.println("Loading MeCab library...");

        String nativeLibPath = "/org/chasen/mecab/native";
        if (System.getProperty("os.name").indexOf("Mac") <= 0) {
            nativeLibPath = nativeLibPath + "/macos";
        } else {
            nativeLibPath = nativeLibPath + "/linux";
        }

        String nativeLibName = System.mapLibraryName("MeCab");
        String nativeLibFilePath = nativeLibPath + "/" + nativeLibName;
        if (MeCab.class.getResource(nativeLibFilePath) == null) {
            System.out.println("Error loading native library: " + nativeLibPath + "/" + nativeLibName);
            System.exit(1);
        }

        // Temporary library folder
        String tempFolder = new File(System.getProperty("java.io.tmpdir")).getAbsolutePath();
        File extractedLibFile = new File(tempFolder, nativeLibName);

        try {
            // Extract resource files
            InputStream reader = MeCab.class.getResourceAsStream(nativeLibFilePath);
            FileOutputStream writer = new FileOutputStream(extractedLibFile);
            byte[] buffer = new byte[1024];
            int bytesRead = 0;
            while ((bytesRead = reader.read(buffer)) != -1) {
                writer.write(buffer, 0, bytesRead);
            }

            writer.close();
            reader.close();

            System.load(extractedLibFile.getAbsolutePath());
        } catch (Exception e) {
            System.err.println(e);
            System.exit(1);
        }
    }
}
